### ISSUE TITLE
Does not Build 

### ISSUE THREAD

**Issue by weedkiller** [akveo/ngx-admin-dotnet-starter#12]
We are testing/trying this but it does not work.

```
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\1_Code\\testbed_Frontend\\ngx-admin\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\1_Code\\testbed_Frontend\\ngx-admin\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\1_Code\testbed_Frontend\ngx-admin\frontend\node_modules\node-sass
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/compiler@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-toaster@8.0.0 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.6 requires a peer of @angular/core@^8.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.6 requires a peer of @angular/forms@^8.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.6 requires a peer of @angular/common@^8.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-language-service@0.9.9 requires a peer of typescript@>= 2.3.1 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-admin-bundle@3.20.2020 No description
npm WARN ngx-admin-bundle@3.20.2020 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

```
Can you also update to .Net 5

**Comment by dmltommywong** [comment]
Hi, have you had any joy?

**Comment by Prefix1802** [comment]
Hi,

Little late but:

Download and install python 2.7 and then 

npm config set python C:\Python27\python.exe
